[package]
name = "jakt-jna-binding"
version = "0.1.0"
edition = "2021"

[lib]
name = "jakt"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.126"
json = "0.12.4"
jakt = { git = "https://github.com/SerenityOS/jakt.git" }
